### ISSUE TITLE
Dereferencing type-punned pointer will break strict-aliasing rules

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-micropython#45]
Introduced by e491b56f5163cd569b1396d2725d280a633986f9:

```
$ make movehub

CC ../../lib/pbio/sys/bluetooth.c
../../lib/pbio/drv/bluetooth/bluetooth_stm32_bluenrg.c: In function 'handle_event':
../../lib/pbio/drv/bluetooth/bluetooth_stm32_bluenrg.c:517:25: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                         pybricks_notify_en = *(uint16_t *)subevt->att_data;
                         ^~~~~~~~~~~~~~~~~~
../../lib/pbio/drv/bluetooth/bluetooth_stm32_bluenrg.c:523:25: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                         uart_tx_notify_en = *(uint16_t *)subevt->att_data;
                         ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
../../micropython/py/mkrules.mk:63: recipe for target 'build/lib/pbio/drv/bluetooth/bluetooth_stm32_bluenrg.o' failed
make[1]: *** [build/lib/pbio/drv/bluetooth/bluetooth_stm32_bluenrg.o] Error 1
make[1]: Leaving directory '/home/laurens/git-pybricks/pybricks-micropython/bricks/movehub'
Makefile:80: recipe for target 'movehub' failed
make: *** [movehub] Error 2
```

Should I upgrade to GCC10?

**Comment by dlech** [comment]
> Should I upgrade to GCC10?

Yes.

>     *(uint16_t *)subevt->att_data

We should probably make this explicit as well instead of assuming little endian.
     
    subevt->att_data[0] | (subevt->att_data[1] << 8);

or just be lazy and look at the LSB since it gets converted to boolean

    subevt->att_data[0]
